spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/solato_db
    username: solato_user
    password: solato_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update